name: onionoo data mirror
on:
  schedule:
    - cron: '5 12/12 * * *'
  workflow_dispatch:
permissions:
        contents: write
jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v4.2.2
      - name: update onionoo data
        run: |
          curl -f --max-time 60 --compressed -o 'details-running-relays.json' \
          'https://onionoo.torproject.org/details?type=relay&running=true&recommended_version=true&fields=fingerprint,or_addresses,first_seen,country_name,guard_probability,advertised_bandwidth'
      - name: commit report
        run: |
          date > date.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add details-running-relays.json date.txt
          git commit -m "Onionoo update"
          git push
